<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>10.0-all</AnalysisLevel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <RootNamespace>Invicta</RootNamespace>
    <AssemblyName>invicta-terrain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invicta.Terrain\Invicta.Terrain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

</Project>
